### ISSUE TITLE
idents with more than one slash fail

### ISSUE THREAD

**Issue by bnomis** [tonsky/datascript#125]
Using an ident such as 

    :string/local/cn

Give an error like

    Invalid token: :string/locale/cn

Is this as intended? It works in datomic.

**Comment by DomKM** [comment]
`:string/locale/cn` is an invalid keyword literal. `(keyword "foo/bar/baz")` creates a keyword but `:foo/bar/baz` is not a valid keyword literal. Stick with valid keywords since behavior that has to do with invalid keywords is not guaranteed. I would change your locale keyword to `:string.locale/cn`.

**Comment by bnomis** [comment]
Thanks
