### ISSUE TITLE
What is touch for?

### ISSUE THREAD

**Issue by kristianmandrup** [tonsky/datascript#148]
I guess it "touches" an entity, like sets it to the equivalent of `null` like an empty file?

```
(defn touch [^Entity e]
  {:pre [(entity? e)]}
  (when-not @(.-touched e)
    (when-let [datoms (not-empty (db/-search (.-db e) [(.-eid e)]))]
      (vreset! (.-cache e) (->> datoms
                                (datoms->cache (.-db e))
                                (touch-components (.-db e))))
      (vreset! (.-touched e) true)))
  e)
```

**Comment by pithyless** [comment]
DataScript follows the Datomic api very closely, so the Datomic documentation is a good resource: http://docs.datomic.com/clojure/#datomic.api/touch

There is also a lot of good getting started material here: https://github.com/tonsky/datascript/wiki/Getting-started

I'm sure @tonsky would appreciate if you ask API questions on gitter instead of opening up GitHub issues: https://gitter.im/tonsky/datascript

**Comment by kristianmandrup** [comment]
Thank you so much. I had not found [Datomic api](http://docs.datomic.com/clojure/#datomic.api) and only just found the gitter channel a minute ago ;) I will ask such questions there in the future.
I'm trying to collect all of the various Datomic/Datascript material out there into a more concise form:
https://github.com/kristianmandrup/datascript-tutorial

You are welcome to chip in if you like.

**Comment by tonsky** [comment]
@kristianmandrup wow! that’s a lot of resources! Added a link here: https://github.com/tonsky/datascript/wiki/Getting-started
