### ISSUE TITLE
Composite tuple support

### ISSUE THREAD

**Issue by schmee** [tonsky/datascript#323]
Tuples were recently added to Datomic and it would be awesome if we could have them in Datascript: https://docs.datomic.com/on-prem/schema.html#composite-tuples.

@tonsky on a scale of "easy, medium, hard", what's your estimate of how difficult this would be to implement for someone who is not familiar with the Datascript code base? I'd love to take a stab at it but I don't really know what I'm getting myself into 😅

**Comment by tonsky** [comment]
Just to clarify: we’re talking about Composite tuples here. You can already store arbitrary vectors in DataScript attributes, so other tuples already kind of work in DataScript.

I’d say it’s medium. The code itself would probably be pretty easy to write, knowing where to put it :) You’ll have to get familiar with a codebase for sure.

Draft plan:

1. Validate schema
2. Build and store some index for normal attribute -> tuple attribute that it invalidates
3. Build a map during transaction for which entities tuples should be updated
4. Update them after transaction

Additionally:

- Make lookups refs work with tuples
- Make queries work with tuples
- Make upserts work with tuples
- Tuple/untuple fns in queries

I would be happy to guide you during the process!

**Comment by jjtolton** [comment]
This is becoming increasingly important for work related-projects.  I think it's important for datahike as well.  @tonsky has anyone communicated intentions to do a PR on this with you? If not I can put aside some time to work on it.

**Comment by tonsky** [comment]
@jjtolton would be great!

**Comment by jjtolton** [comment]
Syntax proposal for datascript tuples:

```clojure 

(def schema
  {
   :student/email               {:db/unique :db.unique/identity}
   :course/id                   {:db/unique :db.unique/identity}
   :semester/year+session       {:db/valueType  :db.type/tuple
                                 :db/tupleAttrs [:semester/year :semester/season]
                                 :db/unique     :db.unique/identity}
   :reg/semester                {:db/valueType :db.type/ref}
   :reg/course                  {:db/valueType :db.type/ref}
   :reg/student                 {:db/valueType :db.type/ref}
   :reg/semester+course+student {:db/valueType  :db.type/tuple
                                 :db/tupleAttrs [:reg/semester :reg/student :reg/course]
                                 :db/unique     :db.unique/identity}
   
   })

(def conn (d/empty-db schema))

(d/transact conn
            [{:semester/year   2018
              :semester/season :fall}
             {:course/id "BIO-101"}
             {:student/first "John"
              :student/last  "Doe"
              :student/email "johndoe@university.edu"}])

(d/transact conn
            [{:reg/course [:course/id "BIO-101"]
              :reg/semester [:semester/year+season [2018 :fall]]
              :reg/student [:student/email "joghndoe@university.edu"]}])


```

What's unclear to me, and I would love some input on, is what the expected behavior is for querying and modifying tuple attributes.  Haven't found it in the documentation yet, but I'll keep looking.  Without that piece, this doesn't immediately confer any benefits over simply using a vector, AFAIK.  Perhaps the benefit is that you can store refs in the tuple and the when transactions update the materialized value of the refs, this will have the desired effect.  For instance:

**NOTE**:  I have no idea if this is the actual Datomic behavior.  These are my thoughts on how it could work and I would love input/feedback:

```clojure
(d/q '[:find (pull ?e [*]) .
       :where
       [_ :reg/semester+course+student (tuple _ _ ?e)]])

;;=> {:db/id         123456
 :student/first "John"
 :student/last  "Doe"
 :student/email "johndoe@university.edu"}

(d/q '[:find (pull ?e [*]) .
       :where
       [?e :db/id 123456]])

;;=> [{:db/id           234561
  :semester/year   2018
  :semester/season :fall}
 {:db/id    345621
  course/id "BIO-101"}
 {:db/id         123456
  :student/first "John"
  :student/last  "Doe"
  :student/email "johndoe@university.edu"}]

(d/transact conn [{:student/email "johndoe@university.edu"
                   :student/last  "Dare"}])

(d/q '[:find (pull ?e [*]) .
       :where
       [?e :db/id 123456]])
;;=> [{:db/id           234561
  :semester/year   2018
  :semester/season :fall}
 {:db/id    345621
  course/id "BIO-101"}
 {:db/id         123456
  :student/first "John"
  :student/last  "Dare"
  :student/email "johndoe@university.edu"}]
```
**NOTE**:  I have no idea if the above is actual Datomic behavior.  These are my thoughts on how it could work and I would love input/feedback.

**Comment by jjtolton** [comment]
Based on discussions in the datahike slack with, revising the behavior to include the following:

- Users don't operate on the composite tuple directly, that's managed by datascript
- In the case of concrete values being the subject of a heterogenous compound tuple:
```clojure 
(def conn (d/empty-db 
{:ref/a+b+c 
  {:db/unique :db.unique/identity 
   :db/valueType :db.type/tuple 
   :db/tupleAttrs [:a :b :c]}}))

(d/transact conn [{:a "a" :b "b" :c "c" :d "d"}]) ;;=> insert tuple
(d/transact conn [{:a "not-a" :b "b" :c "c" :d "d"}]) ;;=> insert different tuple
(d/transact conn [{:a "a" :b "b" :c "c" :d "not-d"}]) ;;=> modifies :d
(d/transact conn [{:db/id [:ref/a+b+c [:a :b :c]] :a "not-a" :b "not-b" :c "not-c"}]) ;;=> modifies tuple values, unrelated to tuple ["not-a" "b" "c"]
```

**Comment by tonsky** [comment]
@jjtolton seems good! 

The main idea of composite tuples is to have an index sorted by multiple values at the same time (tuple). So you’d have a quick way to find an entity that has `a="a" & b="b" & c="c"`. Querying parts of tuple would be physically impossible though, because there’s only one index and it’s sorted in the order tuple arguments are specified. Here:

```
:where [_ :reg/semester+course+student [_ _ ?e]]
```

`:reg/semester+course+student` is sorted by `:semester` first, so no way to find all values with particular `:student`.

But this should be fine—you can always just query the attribute in question instead:

```
:where [_ :student ?e]
```

Upserts should work as you described, I agree. I also think this should be possible too:

```
(d/transact conn [{:ref/a+b+c [:a :b :c] :a "not-a" :b "not-b" :c "not-c"}]) ;;=> modifies tuple values, unrelated to tuple ["not-a" "b" "c"]
```

For all purposes tuple is just another attribute, and as I imagine it we won’t need to program any special support for upsert, lookup refs, queries etc. It should just work.

The only truly new part is that its value should be updated by DataScript automatically, which happens on transactions. This is the main area of the work for tuple support. As I understand it.

**Comment by jjtolton** [comment]
@tonsky Sounds great.  Looking through the code, the two areas that seem most import to identity are schema creation (probably [here](https://github.com/tonsky/datascript/blob/master/src/datascript/db.cljc#L591)) and in the transaction machinery (around [here](https://github.com/tonsky/datascript/blob/master/src/datascript/db.cljc#L1105)).  

It looks like most of the work is going to take place in the `map?` [section](https://github.com/tonsky/datascript/blob/master/src/datascript/db.cljc#L1119).  

I feel like I'm missing a piece but if this is the right direction it'll probably click sooner or later.

**Comment by jjtolton** [comment]
Also I misstated -- this should have been 
```clojure 
(d/q '[:find ?e :where [?e :ref/a+b+c ["a" "b" "c"]]) ;;=> 12345
(d/transact conn [{:ref/a+b+c ["a" "b" "c"] :a "not-a" :b "not-b" :c "not-c"}]) ;;=> :ok 
(d/q '[:find ?e :where [?e :ref/a+b+c ["not-a" "not-b" "not-c"]]) ;;=> 12345
```

**Comment by jjtolton** [comment]
This brings up one more question.  What should the behavior in this situation be?

```clojure 
(d/q '[:find ?e :where [?e :ref/a+b+c ["a" "b" c"]]) ;;=> 12345
(d/pull '[*] 12345) ;;=> {:db/id 12345 :a "a" :b "b" :c "c" :d "d"}
(d/q '[:find ?e :where [?e :ref/a+b+c ["x" "y" z"]]) ;;=> 54321
(d/pull '[*] 54321) ;;=> {:db/id 12345 :a "x" :b "y" :c "z" :d "!!!"}
(d/transact conn [{:ref/a+b+c ["a" "b" "c"] :a "x" :b "y" :c "z"}]) ;;=> ???
(d/q '[:find ?e :where [?e :ref/a+b+c ["x" "y" z"]]) ;;=> ???
(def ??? (d/q '[:find ?e :where [?e :ref/a+b+c ["x" "y" z"]]))
(d/pull '[*] ???) ;;=> ???
```

**Comment by tonsky** [comment]
```
(d/pull '[*] 12345) ;;=> {:db/id 12345 :a "a" :b "b" :c "c" :d "d"}
```

should also return `:ref/a+b+c`:

```
(d/pull '[*] 12345) ;;=> {:db/id 12345 :a "a" :b "b" :c "c" :d "d" :ref/a+b+c ["a" "b" "c"]}
```

As for this:

```
(d/transact conn [{:ref/a+b+c ["a" "b" "c"] :a "x" :b "y" :c "z"}]) ;;=> ???
```

I think this should be an upsert conflict. This is kind of similar to how it would work with lookup refs, e.g.:

```
(d/transact conn [{:db/id [:url "abc"] :url "def"}])
```

Algorithm is as follows:

- start looking at the map, assuming we don’t know which entity we are inserting
- See `:db/id [:url "abc"]`. Aha, we resolve it to `:db/id 5` for example
- Continue looking at the map. See `:url "def"`. Since `:url` is unique, we check to see if there’s entity with `:url "def"`. If there isn’t, that’s cool, that means transaction was meaning to change `[5 :url "abc"]` to `[5 :url "def"]` and we know it can do so since there’s no conflict.
- If, alternatively, we see that `:url "def"` exists and corresponds to entity 7, that is a conflict. We already know that part of the map points toward 5, but another part points toward 7. Each one on their own is fine, together, there’s a problem. We throw an exception.

In case of tuples, trick is that conflicting attibute doesn’t exist explicitly in a transaction. You’ll have to create it (as a part of generating tuple part of tx, and then check for conflict.

As I imagine that would work:

- Transacting `{:ref/a+b+c ["a" "b" "c"] :a "x" :b "y" :c "z"}`
- Processing `:ref/a+b+c ["a" "b" "c"]`. That attribute is unique, so treat it is an upsert indicator. Resolve to `{:db/id 12345}`
- Processing `:a "x"`. Just an `[:db/add 12345 :a "x"]`
- Processing `:b "y". Just an `[:db/add 12345 :b "y"]`
- Processing `:c "z". Just an `[:db/add 12345 :c "z"]`
- Now for the tricky part. We are updating tuple attributes. That means we have to check if we need to update tuple. In our case we have all three attrs, so we have to. Add to transaction: `[:db/add 12345 :ref/a+b+c ["x" "y" "z"]]`
- Now we need to process output from the previous step too! We see `:ref/a+b+c` is a unique attribute, so we check if entity with such attribute exists.
- It does! And since our `:db/id` is concrete (not tempid), that means we have a conflict! Throw.

Now, it would work differently if we didn’t have `:ref/a+b+c ["x" "y" "z"] = 54321` in the db already — it would’ve been a simple update.

If we didn’t transact `:ref/a+b+c ["a" "b" "c"]`. Then at the last step we would have `[:db/add -1 :ref/a+b+c ["x" "y" "z"]]`, and even though `:ref/a+b+c ["x" "y" "z"]` already exists, we resolve it to 54321 and deduce that `-1 == 54321` now. Whole operation transforms into upsert.

One interesting special case: this shold be possible too:

```
`{:ref/a+b+c ["a" "b" "c"] :a "x"}`
```

We figure out `{:db/id 12345}` + `[:db/add 12345 :a "x"]`. Then since 12345 already has `:b` and `:c` defined, we have to pull them out to update tuple. So we add `[:db/add 12345 :ref/a+b+c ["x" "b" "c"]]`. From here on, if `:ref/a+b+c ["x" "b" "c"]` exists, we throw, if not, we don’t.

This might sound complicated, but this is actually a recursive algorithm that just goes over entity map and expands it to series of trivial :db/adds :db/retracts. It handles most of the stuff already too (upserts, tempids). The trick is to add tuple update operation to it. See `transact-tx-data` and `explode` in https://github.com/tonsky/datascript/blob/master/src/datascript/db.cljc

**Comment by tonsky** [comment]
One more tip: direct updating of tuples is not allowed. If you see tuple attribute, it means “do a lookup and identify entity id”, kind of the same as lookup refs do.

```
{:ref/a+b+c ["x" "y" "z"]}
```

means ”find an entity with `:ref/a+b+c ["x" "y" "z"]` and use its db/id for this map”.

In vector form, if you do this:

```
[:db/add 12345 :ref/a+b+c ["x" "y" "z"]]
```

it means the same: find `:ref/a+b+c ["x" "y" "z"]` and compare it with 12345. If they match, this is a no-op. If they don’t, this is an exception. This is an artificial example, you probably will never see it done intentionally. But this behaviour follows from the internal logic of how transactions expand.

This is a bit more useful:

```
[:db/add -1 :ref/a+b+c ["x" "y" "z"]]
```

It means “find `:ref/a+b+c ["x" "y" "z"]` and set -1 to its ids for the rest of the transaction”. If there’s no `:ref/a+b+c ["x" "y" "z"]` it should throw.

All this will probably happen automatically. It already works this way with upserts and unique attributes. The only difference is that in some context you might transact/change unique attribute directly (if there’s no conflict). Tuple attributes are only allowed in contexts of “let’s figure out what id of that entity is” and are never translated in an actual insert/update. Insert/update is handled entirely by DataScript internally.

Hope that makes sense. Feel free to ask anything :)

**Comment by jjtolton** [comment]
Only question I have left.  In the case of sequential entities on transactions:

```clojure 
(d/q '[:find ?e :where [?e :a "a"] [?e :b "b"] [?e :c "c"]] @conn) ;;=> 12345

(d/transact conn [:db/add [:ref/a+b+c ["a" "b" "c"]] :a "x"])

(d/q '[:find ?e :where [?e :a "x"] [?e :b "b"] [?e :c "c"]] @conn) ;;=> 12345 ?? (provided no conflicts)
``` 

Do sequential entity transactions also change `ref/a+b+c` or would that "bypass" the system and leave things in a bad state?  Thanks again @tonsky your explanations have been very helpful.

**Comment by tonsky** [comment]
> Do sequential entity transactions also change ref/a+b+c or would that "bypass" the system and leave things in a bad state?

Sequential transaction are as good as map transactions. They are both first-class sitizens. I don’t think there should be a way to bypass tuple system, I see no value in it.

Any attribute update _must_ also change ref value. That’s the proposition of tuples. Simple rule: if, at the end of the transaction, entity has enough attributes to calculate tuple, tuple value is inserted/updated. If there’s not enough attributes, tuple value is retracted.

```
(d/pull '[*] 12345) ;;=> {:db/id 12345 :a "a" :b "b"}

(d/transact conn [[:db/add 12345 :c "c"]])
(d/pull '[*] 12345) ;;=> {:db/id 12345 :a "a" :b "b" :c "c" :ref/a+b+c ["a" "b" "c"]}

(d/transact conn [[:db/add 12345 :a "x"]])
(d/pull '[*] 12345) ;;=> {:db/id 12345 :a "x" :b "b" :c "c" :ref/a+b+c ["x" "b" "c"]}

(d/transact conn [[:db/retract 12345 :a "x"]])
(d/pull '[*] 12345) ;;=> {:db/id 12345 :b "b" :c "c"}
```

Hope that answers your question.

**Comment by jjtolton** [comment]
The reason I ask is because the obvious path would be to convert 
```clojure 
(d/transact conn [{:ref/a+b+c ["a" "b" "c"] :a "x" :b "y" :c "z"}])
```
to 
```clojure 
(d/transact conn [
  [[:ref/a+b+c ["a" "b" "c"]] :ref/a+b+c ["x" "y" "z"]]
  [[:ref/a+b+c ["a" "b" "c"]] :a "x"] 
  [[:ref/a+b+c ["a" "b" "c"]] :b "y"]
  [[:ref/a+b+c ["a" "b" "c"]] :c "z"]
])
```
provided the second did not require validation.  I'm going to need to spend some time thinking about how to do the second step efficiently.

**Comment by tonsky** [comment]
Actually it should expand into smth like

```
(d/transact conn [
  [:db/add 12345 :a "x"] 
  [:db/add 12345 :b "y"]
  [:db/add 12345 :c "z"]
  [:db/add 12345 :ref/a+b+c ["x" "y" "z"]]
])
```

I don’t know, for the sake of validation just put some metadata flag on the last vector. Like

```
^{:db/generated true} [:db/add 12345 :ref/a+b+c ["x" "y" "z"]]
```

That way if user tries to change tuple they will get an exception, but it’s something you produced during tx expansion, it’ll be fine.

**Comment by jjtolton** [comment]
Slick!  

> That way if user tries to change tuple they will get an exception, but it’s something you produced during tx expansion, it’ll be fine.

**Comment by jjtolton** [comment]
However, if the user does this

```clojure
(d/transact conn [
  [:db/add 12345 :a "x"] 
  [:db/add 12345 :b "y"]
  [:db/add 12345 :c "z"]
  [:db/add 12345 :ref/a+b+c ["x" "y" "z"]]
])
```
we would still need to check each sequential entity for being part of a tuple.  I can't see a way around that right now.  Will have to think about it.

**Comment by jjtolton** [comment]
@tonsky looks like you've had to tackle this problem already.  I think using a technique like you use [here] but adapted to something like 
```clojure
(is-tuple-attr? db a)
```
might be the predicate I need to create.

**Comment by tonsky** [comment]
Yes, something like `is-tuple-attr?` would be needed. Those are precalculated on schema creation stage, so checking them are quite fast.

**Comment by jjtolton** [comment]
I'm thinking it may be necessary to create an additional container to track allocated tuple ids in the same way allocated temp ids are created.  I imagine it would go about [here](https://github.com/tonsky/datascript/blob/master/src/datascript/db.cljc#L1113) and look something like 

```clojure
    (let [[entity & entities] es
          db                  (:db-after report)
          {:keys [tempids]}   report
          tuple-ids            {}]
      (cond
        (empty? es)
```

Otherwise I wouldn't be sure how to handle the multiple-sequential-entity situation.

**Comment by jjtolton** [comment]
This also brings up one more important issue.  Can composite tuples share attributes?  If so, how is that resolved?  And is a tuple only created when all attributes are specified?  Or if just one is specified?

```clojure
(def schema 
  {:ref/a+b    {:db/tupleAttrs [:a :b] ...}
   :ref/a+b+c  {:db/tupleAttrs [:a :b :c] ...}})
```
etc.  I'll check the documentation again but I didn't see anything specifically forbidding that.

**Comment by arichiardi** [comment]
Sorry to barge in, following this nice conversation now. My 2c on the last question:

I think I would expect composite tuples to be able to share their attributes.
Probably also two composite keys with different names but exactly the same attributes is a valid use case.

**Comment by tonsky** [comment]
> Can composite tuples share attributes?

Yes. Tuple is just some deduced (calculated) state. Tuple is only created once all attributes it needs are set on entity:

```
:a "a" => nothing
:a "a", :b "b" => nothing
:a "a", :b "b", :c "c" => :ref/abc ["a" "b" "c"]
```

If you have two tuples, `:ref/ab` and `:ref/bc`, then:

```
:a "a" => nothing
:a "a", :b "b" => :ref/ab ["a" "b"]
:a "a", :b "b", :c "c" => :ref/ab ["a" "b"] :ref/bc ["b" "c"]
:b "b", :c "c" => :ref/bc ["b" "c"]
:a "a", :c "c" => nothing
```

Having multiple tuples is ok, it’s just multiple attributes on an entity. Nothing special about it.

**Comment by tonsky** [comment]
>  I imagine it would go about here and look something like

You don’t need to accumulate tuples in `transact-tx-data`. Once `:db/add` / `:db/retract` is emitted (added to the report), check if it was about tuple attribute, and then maybe emit tuple changes. It’s sort of “post-processing” of what comes out of `transact-add`/`transact-retract-datom` here https://github.com/tonsky/datascript/blob/a769e0ff0e9b2b8d1be4a0933729b5af782a20ee/src/datascript/db.cljc#L1231-L1242

**Comment by jjtolton** [comment]
Just an update, I've tried and failed at this several times now -- a lot of it has to do with being slammed with work and not having time to do proper analysis, apologies.  If someone else wants to pick this up, go ahead.  I'm not sure when I'll have time to work on this, unfortunately.

**Comment by tonsky** [comment]
that’s alright, @jjtolton, I’ll be working on it soon as part of ClojuristsTogether Summer of Bugs. Thanks for trying!

**Comment by jjtolton** [comment]
When you go to work on this -- I'm working with Datomic now using tuples quite frequently.  The actual behavior differs significantly enough that it would be worth verifying before continuing.  Happy to be a resource on behavior.  The key difference is that this ` [:db/add 12345 :ref/a+b+c ["x" "y" "z"]]` **never** happens at the user level.  Additionally you cannot query by tuple.  You simply query by the attributes:

```
[?e :a ?x]
[?e :b ?y]
[?e :c ?z]
```
never this:
```
[?e :ref/a+b+c [?x ?y ?z]]
```

**Comment by tonsky** [comment]
> [:db/add 12345 :ref/a+b+c ["x" "y" "z"]] never happens at the user level

Yes. That’s the plan.

>  Additionally you cannot query by tuple.

What do you mean? Query by individual attributes? Or whole tuple? What’s the point of having tuples then?

**Comment by jjtolton** [comment]
To be more complete:
```
(d/create-database "datomic:mem://upsert-test-0")
  (def conn (d/connect "datomic:mem://upsert-test-0"))
  (d/transact conn [{:db/ident       :a
                      :db/valueType   :db.type/long
                      :db/cardinality :db.cardinality/one}
                     {:db/ident       :b
                      :db/valueType   :db.type/long
                      :db/cardinality :db.cardinality/one}
                     {:db/ident       :c
                      :db/valueType   :db.type/long
                      :db/cardinality :db.cardinality/one}
                     {:db/ident       :ref/a+b+c
                      :db/valueType   :db.type/tuple
                      :db/tupleAttrs  [:a :b :c]
                      :db/cardinality :db.cardinality/one
                      :db/unique      :db.unique/identity}])


  (d/transact conn [{:a 1 :b 2 :c 3}])
  (d/q '[:find ?e ?m
         :where
         [?e :ref/a+b+c ?m]]
       (d/db conn))
;;=> "#{[17592186045418 [1 2 3]]}

  (d/transact conn [{:a 1 :b 2 :c 3 :ref/a+b+c [2 2 3]}]) ;;=> exception, upsert conflict

  (d/transact conn [{:a 1 :ref/a+b+c [2 2 3]}])
(d/q '[:find ?e ?m
         :where
         [?e :ref/a+b+c ?m]]
       (d/db conn))
;;=> "#{[17592186045420 [1 nil nil]] [17592186045418 [1 2 3]]}
;; note: this is probably not what was expected, the :ref/a+b+c [2 2 3] seems to have been completely ignored


;; suprisingly, this does work (changing a=1 to a=2)
(d/transact conn [{:a 2 :b 2 :c 3
                     :ref/a+b+c [1 2 3]}])

(d/q '[:find ?e ?m
         :where
         [?e :ref/a+b+c ?m]]
       (d/db conn))
;;=> "#{[17592186045420 [1 nil nil]] [17592186045418 [2 2 3]]}

;; running again causes upsert conflict
(d/transact conn [{:a 2 :b 2 :c 3
                     :ref/a+b+c [1 2 3]}]) ;; upsert conflict
```

So that's the basics.  

It will be worth putting some thought into scope as tuples can also be ref types (that's kind of where my head exploded when working on this).  

On pulls, as an FYI:

```
(d/pull conn [*] [[:ref/a+b+c [1 2 3]]) ;;=> exception
```

Okay, jeeze, I'm glad I checked myself.  On queries:
```
;; suprisingly to me, this works
(d/q '[:find ?e
         :where
         [?e :ref/a+b+c [2 2 3]]]
       (d/db conn))

```
however, this does not:
```
(d/q '[:find ?e ?a
         :where
         [?e :ref/a+b+c [?a 2 3]]
         [?e :a ?a]]
       (d/db conn)) ;;=> {}

(d/q '[:find ?e ?a
         :where
         [?e :ref/a+b+c [?a 2 3]]]
       (d/db conn)) ;;=> {}
```

**Comment by tonsky** [comment]
Sorry I got this wrong:

```
:a "a" => nothing
:a "a", :b "b" => nothing
:a "a", :b "b", :c "c" => :ref/abc ["a" "b" "c"]
```

What happens instead is that missing attrs are filled with `nil`. If all tuple attrs are missing, only then tuple itself is retracted.

```
:a "a" => :ref/abc ["a" nil nil]
:a "a", :b "b" => :ref/abc ["a" "b" nil]
:a "a", :b "b", :c "c" => :ref/abc ["a" "b" "c"]
```
