### ISSUE TITLE
Add support for Datomic Pull API

### ISSUE THREAD

**Issue by asmala** [tonsky/datascript#37]
The newly announced Datomic Pull API (see [blog post](http://blog.datomic.com/2014/10/datomic-pull.html) and [API docs](http://docs.datomic.com/pull.html)), could streamline data retrieval in many cases where we'd currently use helper functions (such as the [ones in datascript-chat](https://github.com/tonsky/datascript-chat/blob/gh-pages/src/datascript_chat/util.cljs)). Support for the Pull API could be a great solution for DataScript.

**Comment by dthume** [comment]
FWIW, I took a stab at implementing `pull` and `pull-many` [here](https://github.com/dthume/datascript/tree/pull-pattern-api). I haven't raised a pull request (although I can if you're interested), because there are still a few bits that need resolved:

- Although the JS API "works", it doesn't correctly handle `:db/id` yet (see the test).
- It isn't yet integrated to the find specifications recently added to query.
- (Probably most importantly) I haven't validated that it completely matches the behaviour of datomic.

The patch also feels a tad large, although a loop/recur based approach was the only way I could see to avoid blowing the stack on large pulls.

**Comment by tonsky** [comment]
@dthume cool, will look into your patch soon. Looks like a lot of good stuff

**Comment by tonsky** [comment]
@dthume wow, thank you for putting that much effort into DS! That’s huge!

I looked into the code, looks good. Test suite is amazing, parser is very good, pull loop is a little bit heavy-weight (still studying your code here).

So, my question is, do you have time and desire to keep working on this until it’s merged into master? Right now there’s couple of changes I want to make (I described them in comments, please take a look). If you want to put some more time and finish this, please create a PR and we can continue discussion/code refinement/reviews there. If you’re busy right now, I can take your commit as-is and continue to work on it by myself.

Anyway, thanks again, this is a really bold addition (biggest in DataScript so far).

**Comment by dthume** [comment]
I'm more than happy to make the changes you've mentioned, although I'll be travelling quite a bit for the next week so they may be slow in coming. I've done most of the small ones, and I'll raise a PR containing everything so far as you suggested, or in case you want to go on ahead with it before I get to it.

**Comment by tonsky** [comment]
Added in 0.9.0 by @dthume
